export const CHANGE = 'CURRENT_USER::CHANGE';
export const LOGIN = 'CURRENT_USER::LOGIN';
export const REGISTER = 'CURRENT_USER::REGISTER';
export const LOGOUT = 'CURRENT_USER::LOGOUT';
export const GET_USER_MOVIES = 'CURRENT_USER::GET_USER_MOVIES';
